spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:student;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: h2
    password: studen123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
